name: Continue staging flow

on:
  pull_request_review:
    types: [submitted]

jobs:
  create-pr-to-release:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'master' && startsWith(github.event.pull_request.head.ref, 'staging/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Auto merge PR
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --squash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version
        id: extract_version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION_PATTERN="([0-9]+)\.([0-9]+)\.([0-9]+)-([0-9]+)"
          if [[ $BRANCH_NAME =~ $VERSION_PATTERN ]]; then
            version="${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.${BASH_REMATCH[3]}(${BASH_REMATCH[4]})"
            echo "Extracted version: $version"
            echo "version=$version" >> $GITHUB_OUTPUT
          else
            echo "No version found in branch name"
            exit 1
          fi

      - name: "Create PR from master to release"
        run: |
          version=${{ steps.extract_version.outputs.version }}
          pr_title="Prepare for $version"
          pr_description="Pull request auto-generated by GitHub Action."
          gh pr create --base release --head master --title "$pr_title" --body "$pr_description"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}