name: Staging deploy flow
run-name: Deploy to staging ${{ inputs.version }}(${{ inputs.build_number}})

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The target version (x.x.x)"
        required: true
      build_number:
        description: "Build number"
        default: '1'
        required: true

env:
  VERSION: ${{ inputs.version }}
  BUILD_NUMBER: ${{ inputs.build_number }}
  STAGING_BRANCH: staging/${{ inputs.version }}-${{ inputs.build_number }}
  CHANGLOG_PATH: fastlane/changelog.txt
  PROJECT_PATH: 'FunNow.xcodeproj/project.pbxproj'

jobs:
  generate-changelog-and-bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Create staging branch"
        id: staging-branch
        run: |
          git config user.email "${{ secrets.ACTION_BOT_EMAIL }}"
          git config user.name "${{ secrets.ACTION_BOT_NAME }}"        
          git checkout -b $STAGING_BRANCH
      
      - name: Generate changelog
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          git log $latest_tag..HEAD --pretty=format:"%s" | grep -E "\[JIRA-[0-9]+\]" | sed 's/^/- /' > $CHANGLOG_PATH
          if [[ `git status --porcelain` ]]; then
            git commit -a -m "Update changelog"
          else
            echo "Same changelog"
          fi

      - name: "Bump version"
        run: |
          sed -i "s/MARKETING_VERSION = [0-9]*\.[0-9]*\.[0-9]*/MARKETING_VERSION = $VERSION/" $PROJECT_PATH
          sed -i "s/CURRENT_PROJECT_VERSION = [0-9]*;/CURRENT_PROJECT_VERSION = $BUILD_NUMBER;/" $PROJECT_PATH
          if [[ `git status --porcelain` ]]; then
            git commit -a -m "Bump version ${{ inputs.version }}(${{ inputs.build_number }})"
          else
            echo "Same version"
          fi

      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ env.STAGING_BRANCH }}
    
      - name: "Create pull request"
        run: |
          pr_title="Generate changelog and bump version for $VERSION($BUILD_NUMBER)"
          pr_description="Pull request auto-generated by GitHub Action."
          gh pr create -B master -H $STAGING_BRANCH -t "$pr_title" -b "$pr_description" --reviewer ${{ github.actor }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}