name: Staging deploy flow
run-name: Deploy to staging ${{ github.event.milestone.title }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The target version (x.x.x)"
        type: string
        required: true
      build_number:
        description: "Build number(`1`, `2`)"
        type: number
        required: true

env:
  VERSION: ${{ inputs.version }}
  BUILD_NUMBER: ${{ inputs.build_number }}
  STAGING_BRANCH: staging/${{ inputs.version }}-${{ inputs.build_number }}
  CHANGLOG_PATH: fastlane/changelog.txt
  PROJECT_PATH: 'FunNow.xcodeproj/project.pbxproj'

jobs:
  Merge-PR:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Create staging branch"
        id: staging-branch
        run: |
          git checkout -b $STAGING_BRANCH
      
      - name: Generate changelog
        run: |
          latest_tag=$(git describe --tags --abbrev=0)
          git log ${latest_tag}..HEAD --pretty=format:"%s" | grep "\[JIRA-\d+\]" | sed 's/^/- /' > $CHANGLOG_PATH
          git commit -m "Update changelog"
          git push origin $STAGING_BRANCH

      - name: "Bump version"
        run: |
          sed -i "s/MARKETING_VERSION = [0-9]*\.[0-9]*\.[0-9]*/MARKETING_VERSION = $VERSION/" $PROJECT_PATH
          sed -i "s/CURRENT_PROJECT_VERSION = [0-9]*;/CURRENT_PROJECT_VERSION = $BUILD_NUMBER;/" $PROJECT_PATH

      - name: "Create pull request"
        run: |
          pr_title="Generate changelog and bump version for $VERSION($BUILD_NUMBER)"
          pr_description="Pull request auto-generated by GitHub Action."
          gh pr create --base master --head $STAGING_BRANCH --title $pr_title --body $pr_description

      - name: "Push changes"
        uses: ad-m/github-push-action@master
        with:
          branch: $STAGING_BRANCH
    