name: Bump version

on:
  workflow_call:
    inputs:
      new_branch:
        type: string
      version:
        type: string
        required: true
      version_file:
        type: string
        default: FunNow.xcodeproj/project.pbxproj

jobs:
  Bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.new_branch }}
          fetch-depth: 0


      - name: "Upgrade version"
        run: |
          # Init
          VERSION_INPUT="${{ inputs.version }}"
          
          rx="^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?"
          # Check validation with format "a.b.c-x"
          if [[ ! $VERSION_INPUT =~ $rx ]]; then
           exit "Invalidate version input"
          fi
          
          # Parse input
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          patch=${BASH_REMATCH[3]}
          buildNumber=${BASH_REMATCH[5]} 
          
          version="$major.$minor.$patch"

          # Write file
          sed -i "s/MARKETING_VERSION = [0-9]*\.[0-9]*\.[0-9]*/MARKETING_VERSION = $version/" ${{ inputs.version_file }}
          sed -i "s/CURRENT_PROJECT_VERSION = [0-9]*;/CURRENT_PROJECT_VERSION = $buildNumber;/" ${{ inputs.version_file }}

      - name: "Git commit"
        id: git
        run: |
          git config user.email "${{ secrets.ACTION_BOT_EMAIL }}"
          git config user.name "${{ secrets.ACTION_BOT_NAME }}"
          git add --all
          if [[ -z "$(git status --porcelain)" ]]; then
             echo "push=false" >> $GITHUB_OUTPUT
          else
             git commit -m "Bump version ${{ inputs.version }}" -a
             echo "push=true" >> $GITHUB_OUTPUT
          fi

      - name: "Push changes"
        if: steps.git.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: ${{ inputs.new_branch }}
