name: Bump version

on:
  workflow_call:
    inputs:
      new_branch:
        type: string
      version:
        type: string
        required: true
      version_file:
        type: string
        default: gradle/libs.versions.toml

jobs:
  Bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        id: checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.new_branch }}
          fetch-depth: 0


      - name: "Upgrade version"
        run: |
          # Init
          VERSION_INPUT="${{ inputs.version }}"
          
          rx="^([0-9]+)\.([0-9]+)\.([0-9]+)(-([0-9]+))?"
          # Check validation with format "a.b.c-x"
          if [[ ! $VERSION_INPUT =~ $rx ]]; then
           exit "Invalidate version input"
          fi
          
          # Parse input
          newMajor=${BASH_REMATCH[1]}
          newMinor=${BASH_REMATCH[2]}
          newPatch=${BASH_REMATCH[3]}
          newStaging=${BASH_REMATCH[5]} 
          
          echo "newMajor: $newMajor"
          echo "newMinor: $newMinor"
          echo "newPatch: $newPatch"
          echo "newStaging: $newStaging"

          # Write file
          # sed -i -E "s/versionMajor = \"([0-9]+)\"/versionMajor = \"$newMajor\"/" ${{ inputs.version_file }}
          # sed -i -E "s/versionMinor = \"([0-9]+)\"/versionMinor = \"$newMinor\"/" ${{ inputs.version_file }}
          # sed -i -E "s/versionPatch = \"([0-9]+)\"/versionPatch = \"$newPatch\"/" ${{ inputs.version_file }}
          # if [[ ! -z $newStaging ]]; then
          #   sed -i -E "s/versionStaging = \"([0-9]+)\"/versionStaging = \"$newStaging\"/" ${{ inputs.version_file }}
          # fi

      # - name: "Git commit"
      #   id: git
      #   run: |
      #     git config user.email "${{ secrets.ACTION_BOT_EMAIL }}"
      #     git config user.name "${{ secrets.ACTION_BOT_NAME }}"
      #     git add --all
      #     if [[ -z "$(git status --porcelain)" ]]; then
      #        echo "push=false" >> $GITHUB_OUTPUT
      #     else
      #        git commit -m "Bump version ${{ inputs.version }}" -a
      #        echo "push=true" >> $GITHUB_OUTPUT
      #     fi

      # - name: "Push changes"
      #   if: steps.git.outputs.push == 'true'
      #   uses: ad-m/github-push-action@master
      #   with:
      #     branch: ${{ inputs.new_branch }}
